language: csharp
solution: "./Autoit_CiscoVPN.sln"

after_success:
       - echo $TRAVIS_BUILD_DIR
       - mkdir ReleasePackage
       - cd $TRAVIS_BUILD_DIR/Autoit_CiscoVPN/bin/Release/
       - cp -v Autoit_CiscoVPN.exe AutoItX3.Assembly.dll AutoItX3.dll Autoit_CiscoVPN.exe.config $TRAVIS_BUILD_DIR/ReleasePackage
       - cd $TRAVIS_BUILD_DIR
       - zip ReleasePackage $TRAVIS_BUILD_DIR
       - ls -R $TRAVIS_BUILD_DIR/ReleasePackage
       - ls -a $TRAVIS_BUILD_DIR/ReleasePackage
       - ls -lh
       - echo "package successful"
             
       
       
jjobs:
  include:
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true

     
