language: csharp
notifications:
  slack:
    rooms:
      - dineshprojects:ZlOk0kblbM5Dk7uzC6dgwuM3#buildstatus
solution: "./Autoit_CiscoVPN.sln"
jobs:
  include:
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true

