version: 1.0.{build}

platform: Any CPU
configuration: Release
build:
 verbosity: normal

before build:
 - cmd: echo restoring nuget
 - cmd: nuget restore
 
artifacts:
 - path: test.zip

 - path: logs

 - path: '**\*.nupkg'
