version: 1.0.{build}

platform: Any CPU
configuration: Release
verbosity: normal

before build:
 - echo restoring nuget
 - cmd: nuget restore
 
artifacts:
 - path: test.zip

 - path: logs

 - path: '**\*.nupkg'
